### ISSUE TITLE
Feature request: in addition to axis=0 | 1, also add axis='index' | 'columns' as valid options

### ISSUE THREAD

**Issue by pybokeh** [HHammond/PrettyPandas#33]
Pandas also allow for this.  See their github closed [issue #9658](https://github.com/pydata/pandas/issues/9658).

I know it's not a big issue, but for someone not coming from numpy background, makes things easier than trying to remember which axis 0 or 1 is.

**Comment by HHammond** [comment]
Fixed in https://github.com/HHammond/PrettyPandas/issues/33

**Comment by HHammond** [comment]
Actually fixed in https://github.com/HHammond/PrettyPandas/pull/48

I did an overhaul of the formatter API to make it compatible with Pandas' `style.format` and I fixed the precision issues at the same time.

**Comment by HHammond** [comment]
'columns', 'index', and 'rows' all work for indexing now.
