### ISSUE TITLE
Please dont use png for code on your intro page. 

### ISSUE THREAD

**Issue by SlyOne** [HHammond/PrettyPandas#39]

**Comment by SlyOne** [comment]
Can recreate your demo from page. 'precision'  fails.

**Comment by HHammond** [comment]
I'm planning to do a big update on this code Thursday and Friday, I'll do my best to fix that and attach a demo notebook instead of relying on PNG only.

Thanks

**Comment by HHammond** [comment]
This change should be up by the end of the day.
