### ISSUE TITLE
PrettyPandas import link broken in pandas 0.19

### ISSUE THREAD

**Issue by ResidentMario** [HHammond/PrettyPandas#42]
The following fails:

`import prettypandas`

With:

`ImportError: No module named 'pandas.core.style'`

The module appears to have moved to `pandas.DataFrame.style` ([changelist](http://pandas.pydata.org/pandas-docs/version/0.19.0/whatsnew.html)), AFAIK.

**Comment by HHammond** [comment]
New PR will fix this https://github.com/HHammond/PrettyPandas/pull/48 forever by no longer using the `Styler` class.
