### ISSUE TITLE
Example doesn't print correctly

### ISSUE THREAD

**Issue by scls19fr** [HHammond/PrettyPandas#47]
Hello,

Example from  https://github.com/HHammond/PrettyPandas/blob/master/Readme.md (see #46 )
doesn't print correctly on Jupyter.

See screenshot
![capture d ecran 2017-11-01 a 18 49 20](https://user-images.githubusercontent.com/109167/32288960-b818ee80-bf35-11e7-92c8-aa082ccbc196.png)

Kind regards

**Comment by scls19fr** [comment]
PrettyPandas was installed using:

    $ pip install git+https://github.com/HHammond/PrettyPandas

**Comment by HHammond** [comment]
I will take a look into it

**Comment by HHammond** [comment]
I think this is because of API changes in Pandas. I have a new PR that will fix this issue.

I've moved PrettyPandas to be less dependant on the underlying `Styler` object with https://github.com/HHammond/PrettyPandas/pull/48 and it will fix this issue.
